services:
  - type: web
    name: predictive-maintenance-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --timeout 120 --workers 1 --threads 4 --bind 0.0.0.0:$PORT backend.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: BREVO_API_KEY
        sync: false
      - key: FROM_EMAIL
        sync: false

